"""Standalone HTML exporter for observability reports."""

from __future__ import annotations

import hashlib
import os
from collections.abc import Sequence
from html import escape
from pathlib import Path
from typing import Any

from pipeline_metrics_exporter.contract import (
    ExportArtifact,
    ExportFormat,
)
from pipeline_metrics_exporter.presentation import (
    flatten_values,
    safe_filename,
)
from pipeline_metrics_exporter.report_loader import (
    LoadedObservabilityReport,
)


HTML_CONTENT_TYPE = "text/html"


class HTMLExportError(Exception):
    """Base exception raised while exporting HTML."""


class HTMLExportFileExistsError(HTMLExportError):
    """Raised when an HTML artifact already exists."""


class HTMLExporter:
    """Export an observability report as standalone HTML."""

    def render(
        self,
        report: LoadedObservabilityReport,
    ) -> str:
        """Render one standalone HTML document."""

        self._validate_report(report)

        title = (
            f"{report.source_type.value.title()} "
            "Observability Report"
        )

        sections = "\n".join(
            self._render_section(
                section_name,
                section_value,
            )
            for section_name, section_value
            in report.sections.items()
        )

        source_metadata = ""

        if report.source_metadata:
            source_metadata = self._render_section(
                "source_metadata",
                report.source_metadata,
            )

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(title)}</title>
  <style>
    :root {{
      color-scheme: light dark;
      font-family: system-ui, sans-serif;
    }}
    body {{
      max-width: 1200px;
      margin: 0 auto;
      padding: 2rem;
      line-height: 1.5;
    }}
    header, section {{
      margin-bottom: 2rem;
    }}
    .metadata {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
      gap: 0.75rem;
    }}
    .metadata div {{
      border: 1px solid currentColor;
      border-radius: 0.4rem;
      padding: 0.75rem;
    }}
    .label {{
      display: block;
      font-size: 0.8rem;
      font-weight: 700;
      opacity: 0.75;
      text-transform: uppercase;
    }}
    table {{
      width: 100%;
      border-collapse: collapse;
    }}
    th, td {{
      border: 1px solid currentColor;
      padding: 0.55rem;
      text-align: left;
      vertical-align: top;
    }}
    th {{
      font-weight: 700;
    }}
    code {{
      white-space: pre-wrap;
      overflow-wrap: anywhere;
    }}
    footer {{
      margin-top: 3rem;
      opacity: 0.7;
    }}
  </style>
</head>
<body>
  <header>
    <h1>{escape(title)}</h1>
    <div class="metadata">
      {self._metadata_item("Source type", report.source_type.value)}
      {self._metadata_item("Report version", report.report_version)}
      {self._metadata_item("Producer version", report.producer_version)}
      {self._metadata_item("Run ID", report.run_id)}
      {self._metadata_item("Generated at", report.generated_at)}
      {self._metadata_item("Status", report.status)}
    </div>
  </header>
  <main>
    {sections}
    {source_metadata}
  </main>
  <footer>
    Generated by Pipeline Metrics Exporter v0.1.0.
  </footer>
</body>
</html>
"""

    def export(
        self,
        report: LoadedObservabilityReport,
        output_directory: str | Path,
        *,
        filename: str | None = None,
        overwrite: bool = False,
    ) -> ExportArtifact:
        """Write a standalone HTML artifact."""

        self._validate_report(report)

        if not isinstance(overwrite, bool):
            raise TypeError("overwrite must be a boolean")

        directory = Path(output_directory).expanduser()
        directory.mkdir(parents=True, exist_ok=True)

        if filename is None:
            filename = (
                f"{report.source_type.value}_"
                f"{safe_filename(report.run_id)}.html"
            )
        else:
            filename = safe_filename(filename)

            if not filename.lower().endswith(".html"):
                filename += ".html"

        artifact_path = directory / filename

        if artifact_path.exists() and not overwrite:
            raise HTMLExportFileExistsError(
                f"HTML artifact already exists: {artifact_path}"
            )

        content = self.render(report)
        encoded = content.encode("utf-8")
        temporary_path = artifact_path.with_name(
            f".{artifact_path.name}.tmp"
        )

        try:
            temporary_path.write_bytes(encoded)
            os.replace(temporary_path, artifact_path)
        except OSError as exc:
            try:
                temporary_path.unlink(missing_ok=True)
            except OSError:
                pass

            raise HTMLExportError(
                "Unable to write HTML artifact "
                f"{artifact_path}: {exc}"
            ) from exc

        checksum = hashlib.sha256(encoded).hexdigest()

        artifact = ExportArtifact(
            format=ExportFormat.HTML,
            path=str(artifact_path.resolve()),
            size_bytes=len(encoded),
            content_type=HTML_CONTENT_TYPE,
            checksum=f"sha256:{checksum}",
            metadata={
                "source_type": report.source_type.value,
                "source_run_id": report.run_id,
                "section_count": len(report.sections),
                "encoding": "utf-8",
                "standalone": True,
                "document_type": "browser-report",
            },
        )

        errors = artifact.validate()

        if errors:
            raise HTMLExportError("; ".join(errors))

        return artifact

    def _render_section(
        self,
        section_name: str,
        section_value: Any,
    ) -> str:
        initial_path = (
            section_name
            if self._is_sequence(section_value)
            else ""
        )

        rows = flatten_values(
            section_value,
            path=initial_path,
        )

        body = "\n".join(
            (
                "        <tr>"
                f"<td><code>{escape(path or section_name)}</code></td>"
                f"<td>{escape(value)}</td>"
                f"<td>{escape(type_name)}</td>"
                "</tr>"
            )
            for path, value, type_name in rows
        )

        heading = escape(
            section_name.replace("_", " ").title()
        )

        return f"""<section>
      <h2>{heading}</h2>
      <table>
        <thead>
          <tr>
            <th>Path</th>
            <th>Value</th>
            <th>Type</th>
          </tr>
        </thead>
        <tbody>
{body}
        </tbody>
      </table>
    </section>"""

    def _metadata_item(
        self,
        label: str,
        value: str,
    ) -> str:
        return (
            "<div>"
            f'<span class="label">{escape(label)}</span>'
            f"<code>{escape(value)}</code>"
            "</div>"
        )

    def _validate_report(
        self,
        report: LoadedObservabilityReport,
    ) -> None:
        if not isinstance(
            report,
            LoadedObservabilityReport,
        ):
            raise TypeError(
                "report must be a LoadedObservabilityReport"
            )

        errors = report.validate()

        if errors:
            raise ValueError("; ".join(errors))

    def _is_sequence(self, value: Any) -> bool:
        return (
            isinstance(value, Sequence)
            and not isinstance(
                value,
                (str, bytes, bytearray),
            )
        )


__all__ = [
    "HTML_CONTENT_TYPE",
    "HTMLExportError",
    "HTMLExportFileExistsError",
    "HTMLExporter",
]
