"""Markdown exporter for RADAR_SERVICE observability reports."""

from __future__ import annotations

import hashlib
import os
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

from pipeline_metrics_exporter.contract import (
    ExportArtifact,
    ExportFormat,
)
from pipeline_metrics_exporter.presentation import (
    flatten_values,
    safe_filename,
)
from pipeline_metrics_exporter.report_loader import (
    LoadedObservabilityReport,
)


MARKDOWN_CONTENT_TYPE = "text/markdown"


class MarkdownExportError(Exception):
    """Base exception raised while exporting Markdown."""


class MarkdownExportFileExistsError(MarkdownExportError):
    """Raised when a Markdown artifact already exists."""


class MarkdownExporter:
    """Export an observability report as readable Markdown."""

    def render(
        self,
        report: LoadedObservabilityReport,
    ) -> str:
        """Render a normalized observability report."""

        self._validate_report(report)

        title = (
            f"{report.source_type.value.title()} "
            "Observability Report"
        )

        lines = [
            f"# {title}",
            "",
            "## Report Metadata",
            "",
            "| Field | Value |",
            "|---|---|",
            (
                "| Source type | "
                f"{self._escape_cell(report.source_type.value)} |"
            ),
            (
                "| Report version | "
                f"{self._escape_cell(report.report_version)} |"
            ),
            (
                "| Producer version | "
                f"{self._escape_cell(report.producer_version)} |"
            ),
            (
                "| Run ID | "
                f"{self._escape_cell(report.run_id)} |"
            ),
            (
                "| Generated at | "
                f"{self._escape_cell(report.generated_at)} |"
            ),
            (
                "| Status | "
                f"{self._escape_cell(report.status)} |"
            ),
        ]

        for section_name, section_value in report.sections.items():
            lines.extend(
                [
                    "",
                    f"## {self._heading(section_name)}",
                    "",
                ]
            )

            initial_path = (
                section_name
                if self._is_sequence(section_value)
                else ""
            )

            flattened = flatten_values(
                section_value,
                path=initial_path,
            )

            lines.extend(
                [
                    "| Path | Value | Type |",
                    "|---|---|---|",
                ]
            )

            for path, value, type_name in flattened:
                lines.append(
                    "| "
                    f"{self._escape_cell(path or section_name)}"
                    " | "
                    f"{self._escape_cell(value)}"
                    " | "
                    f"{self._escape_cell(type_name)}"
                    " |"
                )

        if report.source_metadata:
            lines.extend(
                [
                    "",
                    "## Source Metadata",
                    "",
                    "| Path | Value | Type |",
                    "|---|---|---|",
                ]
            )

            for path, value, type_name in flatten_values(
                report.source_metadata
            ):
                lines.append(
                    "| "
                    f"{self._escape_cell(path)}"
                    " | "
                    f"{self._escape_cell(value)}"
                    " | "
                    f"{self._escape_cell(type_name)}"
                    " |"
                )

        lines.extend(
            [
                "",
                "---",
                "",
                (
                    "Generated by Pipeline Metrics Exporter "
                    "v0.1.0."
                ),
                "",
            ]
        )

        return "\n".join(lines)

    def export(
        self,
        report: LoadedObservabilityReport,
        output_directory: str | Path,
        *,
        filename: str | None = None,
        overwrite: bool = False,
    ) -> ExportArtifact:
        """Write a Markdown artifact."""

        self._validate_report(report)

        if not isinstance(overwrite, bool):
            raise TypeError("overwrite must be a boolean")

        directory = Path(output_directory).expanduser()
        directory.mkdir(parents=True, exist_ok=True)

        if filename is None:
            filename = (
                f"{report.source_type.value}_"
                f"{safe_filename(report.run_id)}.md"
            )
        else:
            filename = safe_filename(filename)

            if not filename.lower().endswith(".md"):
                filename += ".md"

        artifact_path = directory / filename

        if artifact_path.exists() and not overwrite:
            raise MarkdownExportFileExistsError(
                "Markdown artifact already exists: "
                f"{artifact_path}"
            )

        content = self.render(report)
        encoded = content.encode("utf-8")
        temporary_path = artifact_path.with_name(
            f".{artifact_path.name}.tmp"
        )

        try:
            temporary_path.write_bytes(encoded)
            os.replace(temporary_path, artifact_path)
        except OSError as exc:
            try:
                temporary_path.unlink(missing_ok=True)
            except OSError:
                pass

            raise MarkdownExportError(
                "Unable to write Markdown artifact "
                f"{artifact_path}: {exc}"
            ) from exc

        checksum = hashlib.sha256(encoded).hexdigest()

        artifact = ExportArtifact(
            format=ExportFormat.MARKDOWN,
            path=str(artifact_path.resolve()),
            size_bytes=len(encoded),
            content_type=MARKDOWN_CONTENT_TYPE,
            checksum=f"sha256:{checksum}",
            metadata={
                "source_type": report.source_type.value,
                "source_run_id": report.run_id,
                "section_count": len(report.sections),
                "encoding": "utf-8",
                "document_type": "human-readable-report",
            },
        )

        errors = artifact.validate()

        if errors:
            raise MarkdownExportError("; ".join(errors))

        return artifact

    def _validate_report(
        self,
        report: LoadedObservabilityReport,
    ) -> None:
        if not isinstance(
            report,
            LoadedObservabilityReport,
        ):
            raise TypeError(
                "report must be a LoadedObservabilityReport"
            )

        errors = report.validate()

        if errors:
            raise ValueError("; ".join(errors))

    def _escape_cell(self, value: Any) -> str:
        return (
            str(value)
            .replace("\\", "\\\\")
            .replace("|", "\\|")
            .replace("\r", " ")
            .replace("\n", "<br>")
        )

    def _heading(self, value: str) -> str:
        return value.replace("_", " ").title()

    def _is_sequence(self, value: Any) -> bool:
        return (
            isinstance(value, Sequence)
            and not isinstance(
                value,
                (str, bytes, bytearray),
            )
        )


__all__ = [
    "MARKDOWN_CONTENT_TYPE",
    "MarkdownExportError",
    "MarkdownExportFileExistsError",
    "MarkdownExporter",
]
